# Netlify configuration
[build]
  publish = "dist"
  command = "npm run build"

# Ensure the admin page is accessible
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
